name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-gnu
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/bytewhiffer.exe
          draft: false
          prerelease: false
